"""check_remaining_drift

Revision ID: 45611e933cff
Revises: 7bba57da5667
Create Date: 2026-09-06 12:58:22.292145
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45611e933cff'
down_revision: Union[str, None] = '7bba57da5667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'completed', 'cancelled', 'no_show', name='appointmentstatus'),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_appointments_branch_id'), 'appointments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.alter_column('blog_posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('blog_posts', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('blog_posts', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_blog_posts_author_id'), 'blog_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_posts_deleted_at'), 'blog_posts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_is_featured'), 'blog_posts', ['is_featured'], unique=False)
    op.create_index(op.f('ix_blog_posts_is_published'), 'blog_posts', ['is_published'], unique=False)
    op.create_index(op.f('ix_blog_posts_published_at'), 'blog_posts', ['published_at'], unique=False)
    op.alter_column('branch_stock', 'stock',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_product_branch_stock', 'branch_stock', type_='unique')
    op.create_index(op.f('ix_branch_stock_branch_id'), 'branch_stock', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_stock_product_id'), 'branch_stock', ['product_id'], unique=False)
    op.create_unique_constraint('uq_branch_stock', 'branch_stock', ['product_id', 'branch_id'])
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('branches', 'working_hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('branches', 'services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_user_product_cart', 'cart_items', type_='unique')
    op.create_index(op.f('ix_cart_items_branch_id'), 'cart_items', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_categories_deleted_at'), 'categories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.alter_column('doctor_availability', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_doctor_availability_branch_id'), 'doctor_availability', ['branch_id'], unique=False)
    op.create_index(op.f('ix_doctor_availability_doctor_id'), 'doctor_availability', ['doctor_id'], unique=False)
    op.alter_column('doctor_branches', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_doctor_branches_branch_id'), 'doctor_branches', ['branch_id'], unique=False)
    op.create_index(op.f('ix_doctor_branches_doctor_id'), 'doctor_branches', ['doctor_id'], unique=False)
    op.alter_column('doctors', 'experience_years',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_doctors_deleted_at'), 'doctors', ['deleted_at'], unique=False)
    op.alter_column('franchise_leads', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'closed', name='franchiseleadstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('franchise_leads', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_franchise_leads_is_read'), 'franchise_leads', ['is_read'], unique=False)
    op.create_index(op.f('ix_franchise_leads_phone'), 'franchise_leads', ['phone'], unique=False)
    op.create_index(op.f('ix_franchise_leads_status'), 'franchise_leads', ['status'], unique=False)
    op.alter_column('lab_reports', 'is_visible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_lab_reports_appointment_id'), 'lab_reports', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_lab_reports_patient_id'), 'lab_reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_reports_test_id'), 'lab_reports', ['test_id'], unique=False)
    op.alter_column('lab_tests', 'home_sampling_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lab_tests', 'home_sampling_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lab_tests', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_lab_tests_branch_id'), 'lab_tests', ['branch_id'], unique=False)
    op.create_index(op.f('ix_lab_tests_deleted_at'), 'lab_tests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notification_events_event_type'), 'notification_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_events_triggered_at'), 'notification_events', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_notification_events_user_id'), 'notification_events', ['user_id'], unique=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order_items', 'discount_snapshot',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'platform_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'delivery_charges',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'grand_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'processing', 'out_for_delivery', 'delivered', 'cancelled', 'refunded', name='orderstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=postgresql.ENUM('cod', 'card', 'online', name='paymentmethod'),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_orders_branch_id'), 'orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_orders_patient_id'), 'orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.drop_constraint('orders_branch_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.alter_column('products', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'requires_prescription',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.alter_column('reviews', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_reviews_is_approved'), 'reviews', ['is_approved'], unique=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_index(op.f('ix_reviews_target_type'), 'reviews', ['target_type'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'branch_manager', 'pharmacy_staff', 'lab_staff', 'doctor', 'patient', name='userrole'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_users_role', table_name='users')
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'address')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'branch_manager', 'pharmacy_staff', 'lab_staff', 'doctor', 'patient', name='userrole'),
               server_default=sa.text("'patient'::userrole"),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_target_type'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_is_approved'), table_name='reviews')
    op.alter_column('reviews', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('products', 'requires_prescription',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('products', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_branch_id_fkey', 'orders', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_patient_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_branch_id'), table_name='orders')
    op.alter_column('orders', 'payment_method',
               existing_type=postgresql.ENUM('cod', 'card', 'online', name='paymentmethod'),
               server_default=sa.text("'cod'::paymentmethod"),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'processing', 'out_for_delivery', 'delivered', 'cancelled', 'refunded', name='orderstatus'),
               server_default=sa.text("'pending'::orderstatus"),
               existing_nullable=False)
    op.alter_column('orders', 'grand_total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'delivery_charges',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'platform_fee',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'subtotal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.alter_column('order_items', 'discount_snapshot',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_notification_events_user_id'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_triggered_at'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_event_type'), table_name='notification_events')
    op.drop_index(op.f('ix_lab_tests_deleted_at'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_branch_id'), table_name='lab_tests')
    op.alter_column('lab_tests', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('lab_tests', 'home_sampling_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('lab_tests', 'home_sampling_available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_lab_reports_test_id'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_patient_id'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_appointment_id'), table_name='lab_reports')
    op.alter_column('lab_reports', 'is_visible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_franchise_leads_status'), table_name='franchise_leads')
    op.drop_index(op.f('ix_franchise_leads_phone'), table_name='franchise_leads')
    op.drop_index(op.f('ix_franchise_leads_is_read'), table_name='franchise_leads')
    op.alter_column('franchise_leads', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('franchise_leads', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'closed', name='franchiseleadstatus'),
               server_default=sa.text("'new'::franchiseleadstatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_doctors_deleted_at'), table_name='doctors')
    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('doctors', 'experience_years',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_doctor_branches_doctor_id'), table_name='doctor_branches')
    op.drop_index(op.f('ix_doctor_branches_branch_id'), table_name='doctor_branches')
    op.alter_column('doctor_branches', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_doctor_availability_doctor_id'), table_name='doctor_availability')
    op.drop_index(op.f('ix_doctor_availability_branch_id'), table_name='doctor_availability')
    op.alter_column('doctor_availability', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_deleted_at'), table_name='categories')
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_branch_id'), table_name='cart_items')
    op.create_unique_constraint('uq_user_product_cart', 'cart_items', ['user_id', 'product_id'])
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('branches', 'services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('branches', 'working_hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint('uq_branch_stock', 'branch_stock', type_='unique')
    op.drop_index(op.f('ix_branch_stock_product_id'), table_name='branch_stock')
    op.drop_index(op.f('ix_branch_stock_branch_id'), table_name='branch_stock')
    op.create_unique_constraint('uq_product_branch_stock', 'branch_stock', ['product_id', 'branch_id'])
    op.alter_column('branch_stock', 'stock',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_blog_posts_published_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_is_published'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_is_featured'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_deleted_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_author_id'), table_name='blog_posts')
    op.alter_column('blog_posts', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('blog_posts', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('blog_posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_branch_id'), table_name='appointments')
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'completed', 'cancelled', 'no_show', name='appointmentstatus'),
               server_default=sa.text("'pending'::appointmentstatus"),
               existing_nullable=False)
    # ### end Alembic commands ###
